const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "web/index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "web/app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "web/styles.css"), "utf8");
const sw = fs.readFileSync(path.join(root, "web/sw.js"), "utf8");
const headers = fs.readFileSync(path.join(root, "web/_headers"), "utf8");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "web/manifest.webmanifest"), "utf8"));

assert.match(html, /<title>彩票夹<\/title>/);
assert.match(html, /data-view="home" aria-label="首页"/);
assert.match(html, /data-view="check" aria-label="票夹"/);
assert.match(html, /data-view="mine" aria-label="设置"/);
assert.doesNotMatch(html, /data-view="random" aria-label="试玩"/);
assert.match(html, /id="ticketAdd"/);
assert.match(html, /id="manualGameTabs"/);
assert.match(html, /id="drawCarouselDots"/);
assert.match(html, /id="latestDraws" class="home-draw-carousel"/);
assert.match(html, /class="home-floating-scan"/);
assert.doesNotMatch(html, /class="home-brand"/);
assert.doesNotMatch(html, /class="page-title"/);
assert.match(html, /styles\.css\?v=3\.4\.1/);
assert.match(html, /id="profitNetValue"/);
assert.doesNotMatch(html, /id="profitSub"/);
assert.match(html, /class="wallet-sticky-shell"/);
assert.match(html, /data-profit-range="all" aria-pressed="true"/);
for (const range of ["7", "30", "90", "180", "360"]) assert.match(html, new RegExp(`data-profit-range="${range}"`));
assert.match(html, /id="homeMonthlyChart"/);
assert.match(html, /data-view-panel="monthly"/);
assert.match(html, /id="dataStatusEntryBtn"/);
assert.match(html, /id="walletMoreBtn"/);
assert.match(html, /id="openManualPickToolBtn"/);
assert.match(html, /class="wallet-floating-add"/);
assert.match(html, /id="walletFilterSummary"/);
assert.match(html, /id="statsYearSelect"/);
assert.match(html, /id="statsMonthSelect"/);
assert.doesNotMatch(html, /class="today-recommend"/);
assert.match(html, /id="drawUpdateNotice"/);
assert.match(html, /正规线下彩票销售渠道/);
assert.ok(html.indexOf("./rules.js") < html.indexOf("./app.js"), "rules must load before app");

assert.equal(manifest.name, "彩票夹");
assert.equal(manifest.display, "standalone");
assert.ok(manifest.icons.some((icon) => icon.sizes === "192x192"));
assert.ok(manifest.icons.some((icon) => icon.sizes === "512x512" && icon.purpose === "maskable"));
assert.match(sw, /networkFirst\(request, DATA_CACHE\)/, "draw JSON should have an offline fallback");
assert.match(headers, /application\/manifest\+json/, "Netlify should serve the manifest with the PWA MIME type");
assert.match(headers, /\/sw\.js[\s\S]*no-cache/, "service worker updates should not be pinned by Netlify cache");
assert.match(app, /LotteryPrizeRules\.evaluateTicket/, "app should use the standalone prize rules module");
assert.match(app, /backupChecksum/, "backup v2 should include integrity checking");
assert.match(app, /renderMonthlyStats/, "monthly statistics should be wired");
assert.match(app, /const APP_VERSION = "3\.4\.1"/);
assert.match(app, /renderWalletTickets/, "electronic ticket wallet should be wired");
assert.match(app, /renderManualTool/, "all-game manual picker should be wired");
assert.match(app, /scrollDrawCarouselToGame/, "latest draws should support swipe and dot navigation");
assert.match(app, /scheduleDrawCarouselAuto/, "latest draws should rotate automatically");
assert.match(app, /openLatestDrawsSheet/, "all latest draws should open in a dedicated sheet");
assert.match(app, /classList\.add\("is-fullscreen"\)/, "all latest draws should use the full-screen sheet");
assert.match(app, /resetPageScroll/, "every primary view transition should reset its scroll position");
assert.match(app, /本地记录 · 非官方票据 · 请以实体票与官方开奖为准/, "wallet tickets must be clearly marked as local records");
assert.doesNotMatch(app, /标记已兑奖|标记兑奖|已恢复为待兑奖/, "the app must not expose a redemption workflow");
assert.match(app, /compactK8/, "Happy8 home cards should use a compact preview");
assert.match(app, /month-stack-segment/, "annual statistics should stack costs by lottery game");
assert.match(app, /openMonthStackDetails/, "monthly bars should expose game-level details");
assert.match(app, /expandedWalletDraws/, "ticket logos should toggle the corresponding draw numbers");
assert.match(app, /isBaseline:\s*true/, "the all-time chart should start from zero");
assert.match(app, /开奖号码尚未更新，请稍后再试/, "stale same-day draw data should be visible");
assert.doesNotMatch(app, /frontend_schedule_inference/, "the frontend must not invent draw issues");
assert.match(sw, /lottery-pocket-v3\.4\.1/);
assert.match(sw, /self\.skipWaiting\(\)/, "new visual assets should activate immediately");
assert.match(sw, /isVersionedAppAsset/, "CSS and JavaScript should prefer fresh network assets");
assert.match(styles, /--safe-top:\s*env\(safe-area-inset-top/, "page safe area must always resolve");
assert.match(styles, /\.home-draw-carousel > \.draw-card[\s\S]*flex:\s*0 0 100% !important/, "carousel must expose one draw card per viewport");
assert.match(styles, /\.home-trend-card::after\s*\{\s*display:\s*none/, "profit trend should blend into the page");
assert.match(styles, /\.wallet-filter-row[\s\S]*grid-template-columns:\s*repeat\(5/, "wallet filters should fit one row without horizontal scrolling");
assert.match(styles, /@keyframes wallet-firework/, "winning tickets should use a firework celebration");
assert.match(styles, /\.wallet-ticket-line \.ball[\s\S]*aspect-ratio:\s*1\s*\/\s*1/, "wallet number balls must stay circular");

console.log("Product v3.4.1 tests passed");
